#App
## temporary directory to store files
TEMP_DIRECTORY: /root/
LOG_DIRECTORY: /root/


## RabbitMQ
RABBITMQ_HOST: rmq:5672
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: root
RABBITMQ_PASSWORD: defpass

## REDIS

REDIS_HOST: redis:6379
REDIS_PORT: 6379
REDIS_PASSWORD: defpass

#Flask
MAX_CONTENT_SIZE: 10000000000



