
version: "3.7"

volumes:
  workingdir: 
    driver: local

services:
  atx-cloud:
    container_name: atx-cloud
    working_dir: /atx-cloud-bin
    image: atx-cloud
    build: . 
    user: 0:0
    ipc: host
    ports:
      - 5000:5000
    #restart: always
    volumes:
      - $PWD/../:/atx-cloud-bin
    environment:
      - TZ=America/New_York
    command: uwsgi --http 0.0.0.0:5000 --module main:app
