#App

LOG_DIRECTORY: /home/ubuntu/app_data/logs
## temporary directory to store files
TEMP_DIRECTORY: /Images
DBPOPULATION_DIRECTORY: /data/dbpopulation
API_DIRECTORY: /home/ubuntu/apiData
WEBPAGE_DIRECTORY: /home/ubuntu/atx-spa-dist/dist
LDATA_DIRECTORY: /Images
#Flask
MAX_CONTENT_SIZE: 10000000000

#JWT
JWT_TOKEN_LOCATION: 
  - headers
  - query_string


## RabbitMQ
RABBITMQ_HOST: rmq:5672
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: root
RABBITMQ_PASSWORD: defpass

## REDIS

REDIS_HOST: redis:6379
REDIS_PORT: 6379
REDIS_PASSWORD: defpass
